### ISSUE TITLE
Currency Selection

### ISSUE THREAD

**Issue by giorgiouboldi** [CodeForAfrica/AfricanSpending.ComparativeScales#2]
When entering the number, I guess you might want to either ask for some indication of the currency, or have a validator that reminds people to enter a currency with the main value.

**Comment by giorgiouboldi** [comment]
This is an open issue since we thought that it could also be about other values and not only currencies (for example areas, heights, weights, etc.). Are we going to consider only money related numbers/comparisons?

**Comment by uf0** [comment]
We go for only money related number
